### PR TITLE
Use InfoAPI for template strings

### PR DESCRIPTION
**Pull request by SOF3**
Actually we could remove the `colorize` call as well since InfoAPI already supports it, but there are some minor differences (e.g. no `&`, `{darkPurple}` instead of `{dark_purple}`, etc.
Also `{player_ping}` will now become `{player ping}`.
In the long term, I recommend deprecating the `{"player_name"}` template too since it would be `{player name}` (or just `{player}` with InfoAPI.

### CODE REVIEW

**Comment by SOF3** [comment]
Actually you need to use pharynx to include InfoAPI properly, but I didn't bother to study what build.php does. Feel free to ask me if you have problems there.

**Review by xRodzMC — APPROVED** [review]
I have to rewrite things about color format. But thank you for the great explanation about this feature. I might work on this later on.

**Comment by SOF3** [comment]
I forgot to delete the .poggit.yml. Direct Poggit builds will no longer work properly; use the builds from the poggit/stable branch instead.

**Comment by SOF3** [comment]
I mean you have to replace your build workflow with the pharynx workflow.

**Comment by xRodzMC** [comment]
> I forgot to delete the .poggit.yml. Direct Poggit builds will no longer work properly; use the builds from the poggit/stable branch instead.

Where, i can replace?

**Comment by SOF3** [comment]
refer to https://github.com/SOF3/timer-pmmp

**Pull request merged**
